# https://numtide.github.io/devshell
[[commands]]
package = "devshell.cli"
help = "Per project developer environments"

[[commands]]
name = "build-docs"
help = "Build the documentation in docs/_build"
command = "just build-docs"

[devshell]
name = "BigEarthNet-Documentation"
packages = [
  # nix-deps-start
  "poetry",
  "python39",
  "just",
  # nix-deps-end
  # required by Sphinx/docutils!
  "stdenv.cc.cc.lib"
  #"gcc-unwrapped", # <- Seems to also work; could switch to it if there are any issues
]

[devshell.startup.poetry]
text = "poetry env use $DEVSHELL_DIR/bin/python && poetry env info && poetry install"
# text = "poetry install"


# poetry env use /full/path/to/python


[[env]]
# required by Sphinx!
name = "LD_LIBRARY_PATH"
eval = "$DEVSHELL_DIR/lib"

[[env]]
name = "POETRY_VIRTUALENVS_PREFER_ACTIVE_PYTHON"
value = true

[[env]]
name = "POETRY_VIRTUALENVS_IN_PROJECT"
value = true
