name: deploy

on:
  # Trigger the workflow on push to main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: "Run the build with tmate debugging enabled"
        required: false
        default: false

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      # Make it reproducible with act
      # just action uses typescript which isn't supported
      # - uses: extractions/setup-just@v1
      - run: curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin --force
      - run: just --version
      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if env.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('env.yml') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          # This needs to be equal to the env name in the justfile!
          activate-environment: ben_docs
          environment-file: lock.yml
          use-only-tar-bz2: true # This needs to be set for caching to work
          # Note that pip depdencies aren't cached!
          miniforge-variant: Mambaforge
          use-mamba: true
      - name: Build documentation and run notebooks
        run: |
          just build
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
      # Deploy the book's HTML to gh-pages branch
      - name: GitHub Pages action
        if: ${{ github.event_name == 'push' || !env.ACT }}
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: bigearthnet_documentation/_build/html
