name: Deploy PR previews
concurrency: preview-${{ github.ref }}
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
permissions: write-all

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - run: nix develop --command build-docs
      - uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: docs/_build
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
