
name: Publish to PyPI

on:
  release:
    types: [published]

# required since it is started from a previous workflow
# env:
#   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  upload_assets:
    name: Create/Upload assets
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:

          python-version: 3.8

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - uses: extractions/setup-just@v1
      - name: Install node dependencies
        run: |
          just install
      - name: Build package
        run: poetry build
      - name: Publish
        run: poetry publish --username ${{ secrets.PYPI_USER }} --password ${{ secrets.PYPI_PWD }}
