name: Test
on:
  push:
    branches: [main]
    # paths-ignore:
    #   - "bigearthnet_documentation/**"
  pull_request:
    branches: [main]
    # paths-ignore:
    #   - "bigearthnet_documentation/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
